import { useState } from 'react';
import { Download, Copy, Check } from 'lucide-react';
import { cn } from '../lib/utils';
import type { AnalysisResult } from '../types/analysis';
import { CATEGORY_REGISTRY } from '../constants';
import { DIAGNOSTIC_GROUPS, METHOD_LABELS, formatDiagnosticScore } from '../types/diagnostics';

interface ExportButtonProps {
  result: AnalysisResult;
}

function formatMarkdown(result: AnalysisResult): string {
  const lines: string[] = [
    '# AI Tone Audit Report',
    '',
    `**Overall Tone:** ${result.overallTone}`,
    '',
    `> ${result.summary}`,
    '',
    '## Response Diagnostics',
    '',
    'Scores are risk/quality indices, not probabilities. Confidence is qualitative and uncalibrated; lexical-rule scores are heuristic.',
    '',
    ...DIAGNOSTIC_GROUPS.flatMap((group) => [
      `### ${group.label}`,
      '',
      ...CATEGORY_REGISTRY.filter((category) => category.group === group.id).map((category) => {
        const assessment = result.assessments[category.id];
        const score = formatDiagnosticScore(result.scores[category.id], assessment);
        const metadata = assessment.status === 'assessed'
          ? `; ${assessment.method === 'lexical_rule' ? 'heuristic ' : ''}${category.kind === 'quality' ? 'quality' : 'risk'} index; ${METHOD_LABELS[assessment.method]}; ${assessment.method === 'lexical_rule' ? 'match' : 'evidence'} confidence: ${assessment.confidence}`
          : '';
        return `- **${category.label} (${category.id})**: ${score}${metadata}. ${assessment.reason}`;
      }),
      '',
    ]),
    '',
    '## Findings',
    '',
    ...result.findings.map(
      (f) => `### ${f.category} (${f.severity} severity)\n> "${f.text}"\n\n${METHOD_LABELS[f.method ?? 'unrecorded']}; ${f.method === 'lexical_rule' ? 'match' : 'evidence'} confidence: ${f.confidence ?? 'unknown'}\n\n${f.explanation}`,
    ),
    '',
    '## Personalization Profile',
    '',
    `**Base Style:** ${result.personalization.baseStyle}`,
    `**Directness:** ${result.personalization.directness}`,
    `**Brevity:** ${result.personalization.brevity}`,
    `**ChatGPT warmth:** ${result.personalization.chatgptCharacteristics.warmth}`,
    `**ChatGPT enthusiasm:** ${result.personalization.chatgptCharacteristics.enthusiasm}`,
    `**ChatGPT headers & lists:** ${result.personalization.chatgptCharacteristics.headersAndLists}`,
    `**ChatGPT emojis:** ${result.personalization.chatgptCharacteristics.emojis}`,
    '',
    '### Custom Instructions',
    '',
    ...result.personalization.customInstructions.map((i) => `- ${i}`),
    '',
    '### Stonewalling Remediation',
    '',
    result.personalization.stonewallingRemediation,
    '',
    `---`,
    `*Generated by AI Tone Auditor — ${new Date().toISOString()}*`,
  ];
  return lines.join('\n');
}

export function ExportButton({ result }: ExportButtonProps) {
  const [copiedMd, setCopiedMd] = useState(false);

  const exportJson = () => {
    const blob = new Blob([JSON.stringify(result, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement('a');
    anchor.href = url;
    anchor.download = `tone-audit-${Date.now()}.json`;
    anchor.click();
    URL.revokeObjectURL(url);
  };

  const copyMarkdown = () => {
    const md = formatMarkdown(result);
    navigator.clipboard.writeText(md).then(() => {
      setCopiedMd(true);
      setTimeout(() => setCopiedMd(false), 2000);
    });
  };

  return (
    <div className="flex items-center gap-2">
      <button
        onClick={exportJson}
        aria-label="Export result as JSON"
        className="flex items-center gap-1.5 px-3 py-1.5 bg-zinc-900 border border-zinc-800 hover:border-zinc-700 text-zinc-400 hover:text-zinc-200 text-[10px] font-mono uppercase tracking-widest rounded transition-all focus:outline-none focus:ring-2 focus:ring-red-500"
      >
        <Download className="w-3 h-3" aria-hidden="true" />
        <span>JSON</span>
      </button>
      <button
        onClick={copyMarkdown}
        aria-label={copiedMd ? 'Markdown copied' : 'Copy result as Markdown'}
        className={cn(
          'flex items-center gap-1.5 px-3 py-1.5 border text-[10px] font-mono uppercase tracking-widest rounded transition-all focus:outline-none focus:ring-2 focus:ring-red-500',
          copiedMd
            ? 'bg-emerald-500/10 border-emerald-500/50 text-emerald-500'
            : 'bg-zinc-900 border-zinc-800 hover:border-zinc-700 text-zinc-400 hover:text-zinc-200',
        )}
      >
        {copiedMd ? (
          <>
            <Check className="w-3 h-3" aria-hidden="true" />
            <span>Copied</span>
          </>
        ) : (
          <>
            <Copy className="w-3 h-3" aria-hidden="true" />
            <span>Markdown</span>
          </>
        )}
      </button>
    </div>
  );
}
